/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/login": {
    post: operations["login_login_post"];
  };
  "/signin": {
    post: operations["add_account_signin_post"];
  };
  "/account": {
    get: operations["get_user_info_account_get"];
  };
  "/account/edit-info": {
    patch: operations["edit_account_account_edit_info_patch"];
  };
  "/account/edit-photo": {
    put: operations["edit_photo_account_edit_photo_put"];
  };
  "/new-folder": {
    post: operations["new_folder_new_folder_post"];
  };
  "/add-logo": {
    post: operations["add_logo_add_logo_post"];
  };
  "/read-all": {
    get: operations["read_all_folders_read_all_get"];
  };
}

export interface components {
  schemas: {
    /** AddAccountInput */
    AddAccountInput: {
      /** Username */
      username: string;
      /** Password */
      password: string;
      /** Email */
      email: string;
    };
    /** AddLogoInput */
    AddLogoInput: {
      /** Folder Id */
      folder_id: number;
      /** Appl No */
      appl_no: string;
    };
    /** Body_edit_photo_account_edit_photo_put */
    Body_edit_photo_account_edit_photo_put: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** EditUserInput */
    EditUserInput: {
      /** Old Password */
      old_password?: string;
      /** New Password */
      new_password?: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginInput */
    LoginInput: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** LoginOutput */
    LoginOutput: {
      /** Username */
      username: string;
      /** Token */
      token: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: string[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
}

export interface operations {
  login_login_post: {
    parameters: {
      header: {
        "auth-token"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LoginOutput"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginInput"];
      };
    };
  };
  add_account_signin_post: {
    parameters: {
      header: {
        "auth-token"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddAccountInput"];
      };
    };
  };
  get_user_info_account_get: {
    parameters: {
      header: {
        "auth-token"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_account_account_edit_info_patch: {
    parameters: {
      header: {
        "auth-token"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditUserInput"];
      };
    };
  };
  edit_photo_account_edit_photo_put: {
    parameters: {
      header: {
        "auth-token"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_edit_photo_account_edit_photo_put"];
      };
    };
  };
  new_folder_new_folder_post: {
    parameters: {
      query: {
        folder_name: string;
      };
      header: {
        "auth-token"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_logo_add_logo_post: {
    parameters: {
      header: {
        "auth-token"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddLogoInput"];
      };
    };
  };
  read_all_folders_read_all_get: {
    parameters: {
      header: {
        "auth-token"?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}

export interface external {}
